export const simpleResponseSchema = {
  type: "object",
  properties: {
    data: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
        },
        required: ["id"],
      },
    },
  },
  required: ["data"],
};

export const simpleSingleFootprintResponseSchema = {
  type: "object",
  properties: {
    data: {
      type: "object",
      properties: {
        id: { type: "string" },
      },
      required: ["id"],
    },
  },
  required: ["data"],
};

// TODO add minItems: 1 to data after confirming with team
export const responseSchema = {
  type: "object",
  properties: {
    data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          specVersion: { type: "string" },
          precedingPfIds: {
            type: "array",
            items: { type: "string" },
          },
          version: { type: "integer" },
          created: { type: "string", format: "date-time" },
          updated: { type: "string", format: "date-time" },
          status: { type: "string" },
          statusComment: { type: "string" },
          validityPeriodStart: { type: "string", format: "date-time" },
          validityPeriodEnd: { type: "string", format: "date-time" },
          companyName: { type: "string" },
          companyIds: {
            type: "array",
            items: { type: "string" },
          },
          productDescription: { type: "string" },
          productIds: {
            type: "array",
            items: { type: "string" },
          },
          productCategoryCpc: { type: "string" },
          productNameCompany: { type: "string" },
          comment: { type: "string" },
          pcf: {
            type: "object",
            properties: {
              declaredUnit: { type: "string" },
              unitaryProductAmount: { type: "string" },
              pCfExcludingBiogenic: { type: "string" },
              pCfIncludingBiogenic: { type: "string" },
              fossilGhgEmissions: { type: "string" },
              fossilCarbonContent: { type: "string" },
              biogenicCarbonContent: { type: "string" },
              dLucGhgEmissions: { type: "string" },
              landManagementGhgEmissions: { type: "string" },
              otherBiogenicGhgEmissions: { type: "string" },
              iLucGhgEmissions: { type: "string" },
              biogenicCarbonWithdrawal: { type: "string" },
              aircraftGhgEmissions: { type: "string" },
              characterizationFactors: { type: "string" },
              ipccCharacterizationFactorsSources: {
                type: "array",
                items: { type: "string" },
              },
              crossSectoralStandardsUsed: {
                type: "array",
                items: { type: "string" },
              },
              productOrSectorSpecificRules: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    operator: { type: "string" },
                    ruleNames: {
                      type: "array",
                      items: { type: "string" },
                    },
                    otherOperatorName: { type: "string" },
                  },
                  required: ["operator", "ruleNames", "otherOperatorName"],
                  additionalProperties: false,
                },
              },
              biogenicAccountingMethodology: { type: "string" },
              boundaryProcessesDescription: { type: "string" },
              referencePeriodStart: { type: "string", format: "date-time" },
              referencePeriodEnd: { type: "string", format: "date-time" },
              secondaryEmissionFactorSources: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    name: { type: "string" },
                    version: { type: "string" },
                  },
                  required: ["name", "version"],
                  additionalProperties: false,
                },
              },
              exemptedEmissionsPercent: { type: "number" },
              exemptedEmissionsDescription: { type: "string" },
              packagingEmissionsIncluded: { type: "boolean" },
              packagingGhgEmissions: { type: "string" },
              allocationRulesDescription: { type: "string" },
              uncertaintyAssessmentDescription: { type: "string" },
              primaryDataShare: { type: "number" },
              dqi: {
                type: "object",
                properties: {
                  coveragePercent: { type: "number" },
                  technologicalDQR: { type: "number" },
                  temporalDQR: { type: "number" },
                  geographicalDQR: { type: "number" },
                  completenessDQR: { type: "number" },
                  reliabilityDQR: { type: "number" },
                },
                required: [
                  "coveragePercent",
                  "technologicalDQR",
                  "temporalDQR",
                  "geographicalDQR",
                  "completenessDQR",
                  "reliabilityDQR",
                ],
                additionalProperties: false,
              },
              assurance: {
                type: "object",
                properties: {
                  assurance: { type: "boolean" },
                  coverage: { type: "string" },
                  level: { type: "string" },
                  boundary: { type: "string" },
                  providerName: { type: "string" },
                  completedAt: { type: "string", format: "date-time" },
                  standardName: { type: "string" },
                  comments: { type: "string" },
                },
                required: [
                  "assurance",
                  "coverage",
                  "level",
                  "boundary",
                  "providerName",
                  "completedAt",
                  "standardName",
                  "comments",
                ],
                additionalProperties: false,
              },
            },
            required: [
              "declaredUnit",
              "unitaryProductAmount",
              "pCfExcludingBiogenic",
              "pCfIncludingBiogenic",
              "fossilGhgEmissions",
              "fossilCarbonContent",
              "biogenicCarbonContent",
              "dLucGhgEmissions",
              "landManagementGhgEmissions",
              "otherBiogenicGhgEmissions",
              "iLucGhgEmissions",
              "biogenicCarbonWithdrawal",
              "aircraftGhgEmissions",
              "characterizationFactors",
              "ipccCharacterizationFactorsSources",
              "crossSectoralStandardsUsed",
              "productOrSectorSpecificRules",
              "biogenicAccountingMethodology",
              "boundaryProcessesDescription",
              "referencePeriodStart",
              "referencePeriodEnd",
              "secondaryEmissionFactorSources",
              "exemptedEmissionsPercent",
              "exemptedEmissionsDescription",
              "packagingEmissionsIncluded",
              "packagingGhgEmissions",
              "allocationRulesDescription",
              "uncertaintyAssessmentDescription",
              "primaryDataShare",
              "dqi",
              "assurance",
            ],
            additionalProperties: false,
          },
          extensions: {
            type: "array",
            items: {
              type: "object",
              properties: {
                specVersion: { type: "string" },
                dataSchema: { type: "string" },
                documentation: { type: "string" },
                data: {
                  type: "object",
                  additionalProperties: true,
                },
              },
              required: ["specVersion", "dataSchema", "documentation", "data"],
              additionalProperties: false,
            },
          },
        },
        required: [
          "id",
          "specVersion",
          "precedingPfIds",
          "version",
          "created",
          "updated",
          "status",
          "statusComment",
          "validityPeriodStart",
          "validityPeriodEnd",
          "companyName",
          "companyIds",
          "productDescription",
          "productIds",
          "productCategoryCpc",
          "productNameCompany",
          "comment",
          "pcf",
          "extensions",
        ],
        additionalProperties: false,
      },
    },
  },
  required: ["data"],
  additionalProperties: false,
};
